name: Generate Profile Stats

on:
  schedule:
    - cron: '0 6 * * *'  # Daily at 6 AM
  workflow_dispatch:

jobs:
  generate-stats:
    name: Generate GitHub Stats
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Generate Activity Graph
        uses: ashutosh00710/github-readme-activity-graph@v1.6.0
        with:
          username: ${{ github.repository_owner }}
          token: ${{ secrets.GITHUB_TOKEN }}
          bg_color: 0d1117
          color: 58a6ff
          line: 58a6ff
          point: ffffff
          area: true
          hide_border: true
          custom_title: "Contribution Activity"
          
      - name: Commit and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          git diff --staged --quiet || git commit -m "Update profile activity graph"
          git push